certgen:
  tolerations:
    - key: "kubernetes.io/hostname"
      operator: "Equal"
      value: "server"
  job:
    tolerations:
      - key: "kubernetes.io/hostname"
        operator: "Equal"
        value: "server"

config:
  envoy:
      #controllerName: "envoy"

deployment:
  pod:
    tolerations:
      - key: "kubernetes.io/hostname"
        operator: "Equal"
        value: "server"
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
      - key: "node.cilium.io/agent-not-ready"
        operator: "Exists"

