apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- https://github.com/cert-manager/cert-manager/releases/download/v1.16.1/cert-manager.yaml
patchesStrategicMerge:
- cert-manager-v1.12.3.yml.patch

