apiVersion: v1
kind: ConfigMap
metadata:
  name: dashy-config
data:
  conf.yml: |-
    pageInfo:
      title: Î£rÃ¨be
      description: ''
      navLinks: []
      logo: https://avatars.githubusercontent.com/u/854278?v=4
    appConfig:
      theme: one-dark
      layout: auto
      iconSize: medium
      language: en
      startingView: default
      defaultOpeningMethod: sametab
      statusCheck: false
      statusCheckInterval: 0
      faviconApi: allesedv
      routingMode: history
      enableMultiTasking: false
      widgetsAlwaysUseProxy: false
      webSearch:
        disableWebSearch: false
        searchEngine: duckduckgo
        openingMethod: sametab
        searchBangs: {}
      enableFontAwesome: true
      enableMaterialDesignIcons: false
      hideComponents:
        hideHeading: false
        hideNav: true
        hideSearch: true
        hideSettings: true
        hideFooter: true
      auth:
        enableGuestAccess: true
        users: []
        enableKeycloak: false
      showSplashScreen: false
      preventWriteToDisk: true
      preventLocalSave: false
      disableConfiguration: false
      allowConfigEdit: true
      enableServiceWorker: false
      disableContextMenu: false
      disableUpdateChecks: false
      disableSmartSort: false
      enableErrorReporting: false
      workspaceLandingUrl: https://todoist.com/app/project/2295534492
    sections:
      - name: HomeLab
        displayData:
          sortBy: default
          rows: 1
          cols: 1
          collapsed: false
          hideForGuests: false
        items:
          - title: PiHole
            icon: https://pi-hole.net/wp-content/uploads/2016/12/cropped-Vortex-R-1-32x32.png
            url: http://dns.lan/admin/
            target: sametab
            id: 0_664_pihole
          - title: Router
            icon: >-
              https://i.pinimg.com/736x/b3/19/ab/b319ab520c5ad2324a8674b6b29bd385.jpg
            url: https://router.lan
            target: sametab
            id: 1_664_router
          - title: Proxmox
            icon: >-
              https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRw4PulZnLbmAdSRCLLvt1qcBb1bz8a_6s_WPqkO0LdOEJqGeoE_rpaeOQDWMMn48fidZI&usqp=CAU
            url: https://proxmox.lan:8006
            target: sametab
            id: 2_664_proxmox
          - title: Minio
            icon: >-
              https://media.trustradius.com/vendor-logos/Mo/K1/MUSXMMWE0L5C-180x180.PNG
            url: http://s3.lan
            target: sametab
            id: 3_664_minio
          - title: NextCloud
            description: ''
            icon: >-
              https://digitiz.fr/wp-content/uploads/2021/07/Nextcloud-Logo.png
            url: https://cloud.erebe.eu
            target: sametab
            id: 4_664_nextcloud
          - title: Tp Link
            icon: >-
              https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVSKp9dbRRuIfzk4IcIfXIUJwD82Hee9PaW1h0yluxG1bQBIsF93zZalkyaPfPFGQZqeE&usqp=CAU
            url: http://192.168.0.159/
            target: sametab
            id: 5_664_tplink
          - title: CyerChef
            icon: >-
              https://gchq.github.io/CyberChef/assets/aecc661b69309290f600.ico
            url: https://gchq.github.io/CyberChef/
            target: sametab
            id: 6_664_cyerchef
          - title: Warpgate
            icon: >-
              https://raw.githubusercontent.com/warp-tech/warpgate/main/warpgate-web/public/assets/logo.svg
            url: https://warp.erebe.eu
            target: sametab
            id: 7_664_warpgate
        icon: ðŸ–¥ï¸
      - name: Work
        displayData:
          sortBy: default
          rows: 1
          cols: 1
          collapsed: false
          hideForGuests: false
        items:
          - title: Gmail
            icon: https://ssl.gstatic.com/ui/v1/icons/mail/rfr/gmail.ico
            url: https://mail.google.com/mail/u/1/#inbox
            target: sametab
            id: 0_419_gmail
          - title: Standup
            icon: >-
              https://ssl.gstatic.com/calendar/images/conferenceproviders/logo_meet_2020q4_192px.svg
            url: >-
              https://meet.google.com/kpj-zhxg-zcz
            target: sametab
            id: 1_419_standup
          - title: AWS
            icon: >-
              https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Amazon_Web_Services_Logo.svg/1280px-Amazon_Web_Services_Logo.svg.png
            url: https://accounts.google.com/o/saml2/initsso?idpid=C00xxgtqv&spid=95999977614&forceauthn=false
            target: sametab
            id: 2_419_aws
          - title: Gitlab
            icon: >-
              https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlLx7YQsTtkOVpABnTs1vmi5mGjxUZ_1c2awP0AlzkUNpyc_66Rh7eRoZ8zOmAmqZUkvc&usqp=CAU
            url: https://gitlab.com/qovery/backend
            target: sametab
            id: 3_419_gitlab
          - title: Qortal
            icon: >-
              https://github.com/Qovery/public-resources/raw/master/qovery_square_new_logo.svg
            url: https://qortal.qovery.com/
            target: sametab
            id: 4_419_qortal
          - title: Jira
            icon: >-
              https://jirasoft.tdf.fr/images/atlassian-jira-logo-large.png
            url: https://qovery.atlassian.net/jira/software/c/projects/COR/boards/34
            target: sametab
            id: 4_49_Jira
          - title: Grafana Business
            icon: https://grafana.com/favicon.ico
            url: https://qortal.qovery.com/grafana/d/lu1G2nn7z/business-v2?orgId=1
            target: sametab
            id: 5_419_grafana
          - title: Grafana Tech
            icon: https://grafana.com/favicon.ico
            url: https://qortal.qovery.com/grafana/dashboards/f/BQmc_dKnz/erebe
            target: sametab
            id: 6_419_grafana
          - title: Console
            icon: https://github.com/Qovery/public-resources/raw/master/qovery_square_new_logo.svg 
            url: https://console.qovery.com/organization/460616f0-94da-4d35-b631-6fa4ed08eb9a/project/b14d2c29-2fbe-42df-9a05-48fa3a66ea88/environments/general
            target: sametab
            id: 7_419_console
          - title: Notion
            icon: >-
              https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png
            url: https://www.notion.so/qovery/
            target: sametab
            id: 8_419_notion
        icon: >-
          https://github.com/Qovery/public-resources/raw/master/qovery_square_new_logo.svg
      - name: News
        icon: ðŸ“
        displayData:
          sortBy: default
          rows: 1
          cols: 1
          collapsed: false
          hideForGuests: false
        items:
          - title: Hackernews
            icon: https://hckrnews.com/favicon.ico
            url: https://hckrnews.com/
            target: sametab
            id: 0_413_hackernews
          - title: /r/programming
            icon: >-
              https://styles.redditmedia.com/t5_2fwo/styles/communityIcon_1bqa1ibfp8q11.png?width=256&s=45361614cdf4a306d5510b414d18c02603c7dd3c
            url: https://www.reddit.com/r/programming/
            target: sametab
            id: 1_413_rprogramming
          - title: /r/rust
            icon: >-
              https://styles.redditmedia.com/t5_2s7lj/styles/communityIcon_pjg3ktzyju771.png?width=256&s=5e99f497418f31f47439c0e8de10553ea9150a00
            url: https://www.reddit.com/r/rust/
            target: sametab
            id: 2_413_rrust
          - title: /r/haskell
            icon: >-
              https://styles.redditmedia.com/t5_2qh36/styles/communityIcon_b3usb2hbvbe11.png?width=256&s=eb39d145e1d2ed489492566ec63938e245e881ed
            url: https://www.reddit.com/r/haskell/top/?t=month
            target: sametab
            id: 3_413_rhaskell
          - title: /r/java
            icon: >-
              https://styles.redditmedia.com/t5_2qhd7/styles/communityIcon_tzuj58g8ax451.png?width=256&s=84724eb7266fa9876bcaa7a42bf09aa49030b38d
            url: https://www.reddit.com/r/java/top/?t=month
            target: sametab
            id: 4_413_rjava
          - title: /r/kotlin
            icon: >-
              https://styles.redditmedia.com/t5_2so2r/styles/communityIcon_p0gr6t26jae41.png?width=256&s=80a5344680fe13c91ab921d34cd1e991dcffb7e1
            url: https://www.reddit.com/r/Kotlin/top/?t=month
            target: sametab
            id: 5_413_rkotlin
          - title: Feedly
            icon: https://feedly.com/favicon.ico
            url: https://feedly.com/
            target: sametab
            id: 6_413_feedly
          - title: NextInpact
            icon: https://www.nextinpact.com/favicon.ico
            url: https://www.nextinpact.com/
            target: sametab
            id: 7_413_nextinpact
      - name: Various
        icon: ðŸª´
        displayData:
          sortBy: default
          rows: 1
          cols: 1
          collapsed: false
          hideForGuests: false
        items:
          - title: Github
            icon: >-
              https://hackingvision.com/wp-content/uploads/2022/04/github-gc8ed0adb3_1280.png
            url: https://github.com/
            target: sametab
            id: 0_745_github
          - title: Coub
            icon: https://coub.erebe.eu/favicon.ico
            url: https://coub.erebe.eu
            target: sametab
            id: 1_745_coub
          - title: Coub
            icon: https://coub.com/favicon.ico
            url: https://coub.com/
            target: sametab
            id: 2_745_coub
          - title: Gmail
            icon: https://ssl.gstatic.com/ui/v1/icons/mail/rfr/gmail.ico
            url: https://mail.google.com/mail/u/0/#inbox
            target: sametab
            id: 3_745_gmail
          - title: Nyaa
            icon: https://nyaa.si/static/favicon.png
            url: https://nyaa.si/?s=seeders&o=desc
            target: sametab
            id: 4_745_nyaa
          - title: Todo
            icon: https://todoist.com/favicon.ico
            url: https://todoist.com/app/project/2295534492
            target: workspace
            id: 5_745_todo

